version: '3.3'

services:

    redis:
        image: redis:alpine
        container_name: frRedis

    api:
        build: .
        container_name: frAPI
        restart: unless-stopped
        env_file: .env
        command: gunicorn -w 1 -b 0.0.0.0:8000 core.wsgi
        working_dir: /app/
        volumes:
            - .:/app/
        ports:
            - "8000:8000"

    celery:
        build: .
        container_name: frCelery
        restart: unless-stopped
        env_file: .env
        working_dir: /app
        command: celery -A core worker -l info
        volumes:
            - .:/app/
        depends_on:
            - redis

    flower:
        build: .
        container_name: notifyFlower
        restart: unless-stopped
        env_file: .env
        working_dir: /app
        volumes:
            - .:/app/
        command: celery --app=core flower
        ports:
            - 5555:5555
        depends_on:
            - redis
